import type { Metadata } from "next";
import "./globals.css";
import { primaryFont } from "../theme/typography";
import { MotionLazy } from "../components/framer-motion";
import { AuthProvider } from "../auth/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={primaryFont.className}>
        <AuthProvider>
          <MotionLazy>
            {children}
          </MotionLazy>
        </AuthProvider>
      </body>
    </html>
  );
}
